// PSEUDOCODE:
// IMPORT { Generator, Names, Order } from 'blockly'
// CREATE arduinoGenerator = new Generator('Arduino')
// // --- Internal tracking state ---
// arduinoGenerator.includes_  = {}   // e.g. { "Servo": "#include <Servo.h>" }
// arduinoGenerator.setupCode_ = {}   // lines to go inside setup()
// arduinoGenerator.variables_ = {}   // global variable declarations
// // ---------- Core overrides ----------
// FUNCTION arduinoGenerator.init(workspace):
//   RESET includes_, setupCode_, variables_ to empty objects
//   CALL default nameDB init if needed
// FUNCTION arduinoGenerator.finish(code):
//   // 'code' = body statements generated by blocks (the "loop" body)
//   includesStr  = JOIN all values of includes_  with newline
//   variablesStr = JOIN all values of variables_ with newline
//   setupStr     = JOIN all values of setupCode_ with newline
//   RETURN:
//     """
//     {includesStr}
//     {variablesStr}
//     void setup() {
//       {setupStr}
//     }
//     void loop() {
//       {code}
//     }
//     """
// FUNCTION arduinoGenerator.scrubNakedValue(line):
//   RETURN line + ';\n'    // ensure statements are semicolon-terminated
// FUNCTION arduinoGenerator.scrub_(block, code, thisOnly):
//   nextBlock = block.nextConnection?.targetBlock()
//   nextCode  = thisOnly ? '' : arduinoGenerator.blockToCode(nextBlock)
//   RETURN code + nextCode
// EXPORT arduinoGenerator
// EXPORT Order object (for precedence: ATOMIC=0, UNARY=1, etc.)
