import { Generator, Names } from "blockly";

// Define operator precedence for Arduino (similar to C++)
const Order = {
  ATOMIC: 0,           // 0 "" ...
  NEW: 1.1,            // new
  MEMBER: 1.2,         // . []
  FUNCTION_CALL: 2,    // ()
  INCREMENT: 3,        // ++
  DECREMENT: 3,        // --
  BITWISE_NOT: 4.1,    // ~
  UNARY_PLUS: 4.2,     // +
  UNARY_NEGATION: 4.3, // -
  LOGICAL_NOT: 4.4,    // !
  TYPEOF: 4.5,         // typeof
  VOID: 4.6,           // void
  DELETE: 4.7,         // delete
  DIVISION: 5.1,       // /
  MULTIPLICATION: 5.2, // *
  MODULUS: 5.3,        // %
  SUBTRACTION: 6.1,    // -
  ADDITION: 6.2,       // +
  BITWISE_SHIFT: 7,    // << >> >>>
  RELATIONAL: 8,       // < <= > >=
  IN: 8,               // in
  INSTANCEOF: 8,       // instanceof
  EQUALITY: 9,         // == != === !==
  BITWISE_AND: 10,     // &
  BITWISE_XOR: 11,     // ^
  BITWISE_OR: 12,      // |
  LOGICAL_AND: 13,     // &&
  LOGICAL_OR: 14,      // ||
  CONDITIONAL: 15,     // ?:
  ASSIGNMENT: 16,      // = += -= *= /= %= <<= >>= ...
  COMMA: 17,           // ,
  NONE: 99             // (...)
};

const arduinoGen = new Generator("Arduino");
arduinoGen.includes_ = {}; // e.g. { "Servo": "#include <Servo.h>" } 
arduinoGen.setupCode_ = {}; // lines to go inside setup()
arduinoGen.variables_ = {}; // global variable declarations


//Overiding Core 
arduinoGen.init = function (workspace) {
  // Reset custom collections
  this.includes_ = {};
  this.definitions_ = {}; // For function definitions etc.
  this.setupCode_ = {};
  this.variables_ = {};

  // Names constructor takes a reserved-words string (comma-separated)
  // These are C/C++ reserved words that should not be used as variable names
  const reservedWords = 'setup,loop,if,else,for,switch,case,while,do,break,continue,return,goto,' +
    'define,include,HIGH,LOW,INPUT,OUTPUT,INPUT_PULLUP,true,false,int,float,long,' +
    'double,char,boolean,byte,short,unsigned,void,string,String,NULL,sizeof,' +
    'analogRead,analogWrite,digitalRead,digitalWrite,pinMode,Serial,delay,millis,micros';
  this.nameDB_ = new Names(reservedWords);
};

arduinoGen.finish = function (code) {
  // Code is the Body Statements Generated by the blocks
  const includesStr = Object.values(this.includes_ || {}).join("\n");
  const definitionsStr = Object.values(this.definitions_ || {}).join("\n");
  const variablesStr = Object.values(this.variables_ || {}).join("\n");
  const setupStr = Object.values(this.setupCode_ || {}).join("\n");

  return `${includesStr}
${variablesStr}
${definitionsStr}

void setup() {
  ${setupStr}
}

void loop() {
  ${code}
}`;
};

arduinoGen.scrubNakedValue = function (line) {
  return line + ';\n';
};

arduinoGen.scrub_ = function (block, code, thisOnly) {
  const nextBlock = block.nextConnection && block.nextConnection.targetBlock();
  if (nextBlock && !thisOnly) {
    const nextCode = arduinoGen.blockToCode(nextBlock);
    return code + nextCode;
  }
  return code;
};

export { arduinoGen };
export { Order };
// EXPORT arduinoGenerator
// EXPORT Order object (for precedence: ATOMIC=0, UNARY=1, etc.)
