import { Generator, Names, Order } from "blockly";

const arduinoGen = new Generator("Arduino");
arduinoGen.includes_ = {}; // e.g. { "Servo": "#include <Servo.h>" } 
arduinoGen.setupCode_ = {}; // lines to go inside setup()
arduinoGen.variables_ = {}; // global variable declarations


//Overiding Core 
arduinoGen.init = function (workspace) {
  // Reseting variables to empty objects
  this.includes_ = {};
  this.setupCode_ = {};
  this.variables_ = {};

  // Call default nameDB init if needed
  this.nameDB_ = new Names(workspace);
  // this.nameDB_.init(); // This might not be needed if Names constructor handles it, but following pattern
};

arduinoGen.finish = function (code) {
  // Code is the Body Statements Generated by the blocks
  const includesStr = Object.values(this.includes_ || {}).join("\n");
  const variablesStr = Object.values(this.variables_ || {}).join("\n");
  const setupStr = Object.values(this.setupCode_ || {}).join("\n");

  return `${includesStr}
${variablesStr}

void setup() {
  ${setupStr}
}

void loop() {
  ${code}
}`;
};

arduinoGen.scrubNakedValue = (line) => {
  return line + ';\n';
};

arduinoGen.scrub_ = (block, code, thisOnly) => {
  const nextBlock = block.nextConnection?.targetBlock()
  const nextCode = thisOnly ? '' : arduinoGen.blockToCode(nextBlock)
  return code + nextCode
};

export { arduinoGen };
export { Order };
// EXPORT arduinoGenerator
// EXPORT Order object (for precedence: ATOMIC=0, UNARY=1, etc.)
