import './builtins'
import './pins'
import './timings'
import './data'
import './sensors'
import './actuators'
import './events'
import './serial'
import './evive'
import './procedures'
// All generator functions are now registered on arduinoGen
